# Generated by Django 5.2.7 on 2025-11-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMicrosite',
        ),
    ]
