# Generated by Django 5.2.5 on 2025-11-20 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticket_number", models.CharField(max_length=50, unique=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, upload_to="tickets/qr_codes/"),
                ),
                (
                    "ticket_image",
                    models.ImageField(blank=True, upload_to="tickets/images/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="order.orderitem",
                    ),
                ),
            ],
        ),
    ]
