# Generated by Django 5.2.5 on 2025-10-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("organizer", "Organizer"), ("viewer", "Viewer")],
                default="Viewer",
                max_length=20,
            ),
        ),
    ]
